/*
 * This file is generated by jOOQ.
*/
package com.viitim.grs.database.tables;


import com.viitim.grs.database.Keys;
import com.viitim.grs.database.Public;
import com.viitim.grs.database.tables.records.PlayerRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Player extends TableImpl<PlayerRecord> {

    private static final long serialVersionUID = 1687973631;

    /**
     * The reference instance of <code>public.player</code>
     */
    public static final Player PLAYER = new Player();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerRecord> getRecordType() {
        return PlayerRecord.class;
    }

    /**
     * The column <code>public.player.id</code>.
     */
    public final TableField<PlayerRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('player_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.player.name</code>.
     */
    public final TableField<PlayerRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.player.nick</code>.
     */
    public final TableField<PlayerRecord, String> NICK = createField("nick", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.player</code> table reference
     */
    public Player() {
        this("player", null);
    }

    /**
     * Create an aliased <code>public.player</code> table reference
     */
    public Player(String alias) {
        this(alias, PLAYER);
    }

    private Player(String alias, Table<PlayerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Player(String alias, Table<PlayerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PlayerRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PLAYER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Player as(String alias) {
        return new Player(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Player rename(String name) {
        return new Player(name, null);
    }
}
