/*
 * This file is generated by jOOQ.
*/
package com.viitim.grs.database;


import com.viitim.grs.database.tables.Player;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.player</code>.
     */
    public static final Player PLAYER = com.viitim.grs.database.tables.Player.PLAYER;
}
